name: dart_code_editor
description: A complete Flutter mobile app for writing, editing, and running Dart code with VS Code-like features.

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3

  # Code Editor & Syntax Highlighting
  flutter_code_editor: ^0.3.0
  code_text_field: ^1.1.0
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0

  # HTTP & API
  dio: ^5.4.0
  http: ^1.1.2

  # Storage & Security
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^12.1.3

  # UI & Animations
  flutter_animate: ^4.3.0
  adaptive_theme: ^3.4.1
  fluttertoast: ^8.2.4

  # File Management
  path_provider: ^2.1.2
  file_picker: ^6.1.1

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/images/
    - assets/icons/
  
  fonts:
    - family: JetBrainsMono
      fonts:
        - asset: assets/fonts/JetBrainsMono-Regular.ttf
        - asset: assets/fonts/JetBrainsMono-Bold.ttf
          weight: 700